# IMPORTING PACKAGES ARE SIMPLE AS TYPING IMPORT

import math as m


from Functions import speak

speak()

print(dir(m))

#  WE ALSO INSTALL MODULES FROM PYTHON MANAGER THAT IS PIP
# PIP INSTALL PACKAGE_NAME

# VIRTUAL ENVIRONMENT IS HAVING SEPARATE INSTALLATION FILE TO INSTALL THE NEW MODULES INIT
# TO START AN VIRTUAL ENVIRONMENT WE TYPE                   PYTHON -M VENV VENV_NAME
# TO ACTIVATE IT WE TYPE                                    venv/Scripts/activate.bat
# WE ALSO CAN CREATE A REQUIREMENT TEXT BY                  PIP FREEZE > REQUIREMENTS.TXT
# TO INSTALL THE REQUIREMENT WE TYPE                        PIP INSTALL -R REQUIREMENTS.TXT
