import os
from iterator import Random


def bank_acc(work_dir):
    full_name = input("ENTER YOUR NAME:  ")
    bank_name = input("ENTER YOUR BANK NAME:  ")
    user_Id = input("ENTER AN ID NUMBER PROVIDED:  ")
    uni_id = Random(full_name)
    val = ''
    for char in uni_id:
        val += char
    print('YOUR UNI-CODE GENERATED BY ITERATOR ', val)
    os.chdir('./db')
    content = [full_name, bank_name, user_Id]
    with open('bank_details.txt', 'w') as f:
        for line in content:
            f.writelines(f'{line}\n')
    os.chdir(work_dir)
    with open('testing', 'w') as f:
        f.write('HEY SUCCESSFULLY CHANGED DIR')
