from configparser import ConfigParser, ExtendedInterpolation
from re import T

parser = ConfigParser(interpolation=ExtendedInterpolation())
parser.read('config.ini')

print(parser.sections())
print(parser.get('setting', 'secret'))
print(parser.options('setting'))

print('db' in parser)
print(parser.get('data_base', 'db_port'))
print(int(parser.get('data_base', 'db_port')))
print(parser.getint('data_base', 'db_port', raw=False))
print(parser.getint('data_base', 'db_port', raw=True))

print(parser.getint('data_base', 'dB_port', fallback=8080))

print(parser.getboolean('setting', 'debug'))

print(parser.get('files', 'python_path'))

try:
    print(parser.get('notFound', 'no'))

except parser.NoSectionError:
    print("you have reached the error generated by parser")

finally:
    print("END OF PROGRAM")
